version: "3"
services:

  web:
    build: ./docker/web
    ports:
      - "80:80"
    volumes:
      - web-sync:/var/www/html:nocopy
      - ~/.composer:/var/www/.composer
    environment:
      - MAGENTO_LANGUAGE=en_US
      - MAGENTO_TIMEZONE=Africa/Cairo
      - MAGENTO_DEFAULT_CURRENCY=EGP
      - MAGENTO_URL=http://local.magento
      - MAGENTO_BACKEND_FRONTNAME=admin
      - MAGENTO_USE_SECURE=0
      - MAGENTO_BASE_URL_SECURE=0
      - MAGENTO_USE_SECURE_ADMIN=0
      - MAGENTO_ADMIN_FIRSTNAME=Admin
      - MAGENTO_ADMIN_LASTNAME=Admin
      - MAGENTO_ADMIN_EMAIL=admin@example.com
      - MAGENTO_ADMIN_USERNAME=admin
      - MAGENTO_ADMIN_PASSWORD=magentorocks1
      - XDEBUG_CONFIG=remote_host=192.168.1.3
      - PHP_IDE_CONFIG=serverName=docker

  db:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"

volumes:
  db-data:
  web-sync:
    external: true